### ISSUE TITLE
On windows, in conda, to run the visualize_data.py I’m receiving `no module: l5kit.data`

### ISSUE THREAD

**Issue by Shreyagupta21** [lyft/l5kit#69] opened 2020-07-15 23:48 UTC
On windows, in conda, to run the visualize_data.py I’m receiving `no module: l5kit.data`
I did the `pip install -r requirements.txt` removing torch and torch vision and tried `pip install -e l5kit`
Is there something I’m missing?

**Comment by lucabergamini** [comment] 2020-07-16 08:57
Hi @Shreyagupta21, I'm assuming the import error is not related to `l5kit.data` only but `l5kit` in general (meaning you would get the same also by trying something like `from l5kit.dataset.dataloader_builder import build_dataloader`), please correct me if that's note the case though.

Can you attach here the output of `pip freeze` maybe? That should tell us a little bit more about your python environment

**Comment by Shreyagupta21** [comment] 2020-07-16 17:31
Hi @lucabergamini, thanks for your help!  The error is related to l5kit in general.  The ouput of pip freeze is:
alabaster==0.7.12
appdirs==1.4.4
asciitree==0.3.3
atomicwrites==1.4.0
attrs==19.3.0
Babel==2.8.0
backcall==0.2.0
black==19.10b0
bleach==3.1.5
cachetools==4.1.1
certifi==2020.6.20
cfgv==3.1.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
commonmark==0.9.1
coverage==5.2
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
distlib==0.3.1
docutils==0.16
entrypoints==0.3
fasteners==0.15
filelock==3.0.12
fire==0.3.1
flake8==3.8.3
future==0.18.2
identify==1.4.23
idna==2.10
imageio==2.9.0
imagesize==1.2.0
ipykernel==5.3.2
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==5.0.4
jedi==0.17.1
Jinja2==2.11.2
joblib==0.16.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.5
jupyter-console==6.1.0
jupyter-core==4.6.3
keyring==21.2.1
kiwisolver==1.2.0
-e git+https://github.com/lyft/l5kit.git@5d2f386234c63bc0eb25445a61fa1398aebf1657#egg=l5kit&subdirectory=l5kit
lyft-dataset-sdk @ git+https://github.com/lyft/nuscenes-devkit@8b55159e89d6318f143bd44dbdfde99ad7ff72e8
MarkupSafe==1.1.1
matplotlib==3.2.2
mccabe==0.6.1
mistune==0.8.4
monotonic==1.5
more-itertools==8.4.0
mypy==0.782
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.0.7
nodeenv==1.4.0
notebook==6.0.3
numcodecs==0.6.4
numpy==1.19.0
opencv-contrib-python-headless==4.3.0.36
opencv-python==4.2.0.34
packaging==20.4
pandas==1.0.5
pandocfilters==1.4.2
parso==0.7.0
pathspec==0.8.0
pickleshare==0.7.5
Pillow==7.2.0
pipenv==2020.6.2
pkginfo==1.5.0.1
plotly==4.8.2
pluggy==0.13.1
pre-commit==2.5.1
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
PTable==0.9.2
py==1.9.0
pycodestyle==2.6.0
pyflakes==2.2.0
Pygments==2.6.1
pymap3d==2.4.1
pyparsing==2.4.7
pyquaternion==0.9.5
pyrsistent==0.16.0
pytest==5.4.3
pytest-cov==2.10.0
python-dateutil==2.8.1
pytz==2020.1
pywin32==228
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole==4.7.5
QtPy==1.9.0
readme-renderer==26.0
recommonmark==0.6.0
regex==2020.6.8
requests==2.24.0
requests-toolbelt==0.9.1
retrying==1.3.3
rfc3986==1.4.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
scikit-learn==0.23.1
scipy==1.5.1
Send2Trash==1.5.0
Shapely==1.7.0
six==1.15.0
snowballstemmer==2.0.0
Sphinx==3.1.1
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
strictyaml==1.0.6
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.1.0
toml==0.10.1
torch==1.5.1
torchvision==0.6.1
tornado==6.0.4
tqdm==4.47.0
traitlets==4.3.3
transforms3d==0.3.1
twine==3.2.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
virtualenv==20.0.25
virtualenv-clone==0.5.4
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
zarr==2.4.0

**Comment by lucabergamini** [comment] 2020-07-16 22:00
Interesting, `l5kit` is installed in your env (in editable mode) so it should be available as a package.

I sadly can't reproduce the error under linux using pip in a virtualenv. The error could be due to:

- using conda; I'm positive we tried it under Windows, but it may be worth trying using only venv and pip still;
- Windows itself. I'm assigning this to @oliver-scheel who has a working `L5Kit` build under Windows


> I did the `pip install -r requirements.txt` removing torch and torch vision and tried `pip install -e l5kit`
> Is there something I’m missing?

Just noticed the additional `pip install -e l5kit`. `pip install -r requirements.txt` should already install also l5kit in editable mode (didn't change the outcome under Linux though)

**Comment by lucabergamini** [comment] 2020-07-17 08:32
Also @Shreyagupta21 , is `visualiza_data.py` something you wrote or are you referring to the notebook we ship? Are you running it from its folder (`examples`) or from somewhere else?

**Comment by Shreyagupta21** [comment] 2020-07-17 17:05
Hello @lucabergamini, Visualize_data.py is the notebook you ship and I'm running it from the examples folder.

**Comment by lucabergamini** [comment] 2020-07-17 17:27
Any chance you can try a fresh env with pip only (no conda)? Can you also paste here the full error stack please? 

I'm sorry but I can't be of much help on Windows sadly :(

**Comment by Shreyagupta21** [comment] 2020-07-17 20:23
I tried a fresh env with pip, but unfortunately it didn't work. This is the full error stack:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7a1e7edc2221> in <module>
      3 import numpy as np
      4 
----> 5 from l5kit.data import ChunkedStateDataset, LocalDataManager
      6 from l5kit.dataset import EgoDataset, AgentDataset
      7 

ModuleNotFoundError: No module named 'l5kit'

**Comment by oliver-scheel** [comment] 2020-07-20 16:48
Hi @Shreyagupta21, thanks for waiting, and sorry about the late reply!
As @lucabergamini said, we mainly develop under Linux, so it took me a while to get a Windows machine running.
But now I have, and am very happy to help you.
Although I have to say, 'unfortunately' for me everything works under Windows - and I am a bit out of guesses here, as pip freeze shows you have l5kit installed ...
Could you tell me more about your system? what windows is it, do you have a CUDA compatible GPU? which version of Pytorch did you install, which python?
Similar to you, I created a new condas environment, installed Pytorch manually and then ran our installer. works.
could you try one more time for me setting up a new condas environment and installing our latest l5kit version? Then, please run python in that activated environment and simply try the line 'from l5kit.data import ChunkedStateDataset, LocalDataManager' - does this already raise the same error (excluding any possible issues with our visualizer example, but I would be amazed if that changed anything).

**Comment by Shreyagupta21** [comment] 2020-07-24 21:30
Hello @oliver-scheel.  I ended up just switching Linux which solved all my issues.  Thanks for trying to help me.

**Comment by oliver-scheel** [comment] 2020-07-27 13:59
Hi @Shreyagupta21 , happy to hear it's working now - hope you enjoy working with L5Kit and please let us there about any further issues!

**Closed by oliver-scheel** 2020-07-27 13:59 UTC
Labels: bug
